"""
Django settings for OUPharmacyManagementApp project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

import cloudinary
import cloudinary.uploader
import cloudinary.api
import os

import dj_database_url
from decouple import config, Csv, Config, RepositoryEnv
from dotenv import load_dotenv
import firebase_admin
from firebase_admin import credentials

from OUPharmacyManagementApp.firebase_config import initialize_firebase

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# DEBUG MODE ; SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
INTERNAL_IPS = os.getenv('INTERNAL_IPS', '127.0.0.1').split(',')
CORS_ALLOW_ALL_ORIGINS = True

# Guest cart sends X-Guest-Session; browser preflight requires explicit allow-list.
from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = (
    *default_headers,
    "x-guest-session",
)

# Application definition
# Local admin (Docker): always trust localhost HTTP origins in addition to env list.
csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
_CSRF_FROM_ENV = [origin.strip() for origin in csrf_origins.split(',') if origin.strip()] if csrf_origins else []
_CSRF_LOCAL = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys([*_CSRF_FROM_ENV, *_CSRF_LOCAL]))

# 'debug_toolbar',
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainApp.apps.MainappConfig',
    'storeApp.apps.StoreappConfig',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'oauth2_provider',
    # 'drf_yasg',
    'corsheaders',
    'cloudinary',
    'django_celery_beat',
    'django_filters',
    'django_crontab',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'OUPharmacyManagementApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'mainApp/templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OUPharmacyManagementApp.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # authentication
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'forgot_password': '5/hour',
        'reset_password': '20/hour',
    },
}

# Build reset-password URL from CLIENT_SERVER to avoid duplicate env routing config.
CLIENT_SERVER = os.getenv('CLIENT_SERVER', '').strip().rstrip('/')
PASSWORD_RESET_FRONTEND_PATH = '/dat-lai-mat-khau'
PASSWORD_RESET_FRONTEND_URL = f'{CLIENT_SERVER}{PASSWORD_RESET_FRONTEND_PATH}' if CLIENT_SERVER else ''

# import pymysql
# pymysql.install_as_MySQLdb()
# Database

# Database chính cho Clinic app
default_db = dj_database_url.config(default=os.getenv('DATABASE_URL_PG'))

# Database riêng cho Store app (ưu tiên STORE_DATABASE_URL_PG)
store_db_url = os.getenv('STORE_DATABASE_URL_PG')
if store_db_url:
    store_db = dj_database_url.config(default=store_db_url)
else:
    # Fallback: dùng chung database nhưng tách schema bằng cách clone config
    store_db = default_db.copy()
    if 'NAME' in store_db:
        # Nếu có tên database, thêm suffix
        store_db['NAME'] = store_db.get('NAME', '') + '_store'

DATABASES = {
    'default': default_db,
    'store': store_db,
}

# Database Router để route models sang database phù hợp
DATABASE_ROUTERS = ['storeApp.db_router.StoreRouter']

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIMEZONE SETTING HERE
# READ DATA : UTC (-7H) ; WRITE DATA : UTC (OKE)

# ValueError at /admin/django_celery_beat/periodictask/ (USE_TZ=TRUE)
USE_TZ = True
TIME_ZONE = 'Asia/Bangkok'
USE_I18N = True

ADMIN_INDEX_TEMPLATE = 'admin/dashboard.html'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


STATICFILES_DIRS = [os.path.join(BASE_DIR, "mainApp", "static")]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
STATIC_URL = 'static/'

AUTH_USER_MODEL = 'mainApp.User'
MEDIA_ROOT = '%s/mainApp/static/' % BASE_DIR
CKEDITOR_UPLOAD_PATH = 'post/'


OAUTH2_INFO = {
    "client_id": os.getenv('OAUTH2_CLIENT_ID'),
    "client_secret": os.getenv('OAUTH2_CLIENT_SECRET')
}

# OAuth2 lifetimes (store / clients). Keep firebase_social + /o/token/ aligned with these.
OAUTH2_ACCESS_LIFETIME_SEC = 12 * 60 * 60  # 12 hours
OAUTH2_REFRESH_LIFETIME_SEC = 30 * 24 * 60 * 60  # 30 days

OAUTH2_PROVIDER = {
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
    'OAUTH2_VALIDATOR_CLASS': 'mainApp.oauth_validators.OUPharmacyOAuth2Validator',
    'ACCESS_TOKEN_EXPIRE_SECONDS': OAUTH2_ACCESS_LIFETIME_SEC,
    # Used by cleartokens + enforced on refresh in OUPharmacyOAuth2Validator
    'REFRESH_TOKEN_EXPIRE_SECONDS': OAUTH2_REFRESH_LIFETIME_SEC,
}


# CLOUDINARY FOLDER UPLOADED
# Uncomment these lines to use Cloudinary for media storage
MEDIA_URL = '/OUPharmacy/'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

cloudinary.config(
    cloud_name=os.getenv('CLOUDINARY_NAME'),
    api_key=os.getenv('CLOUDINARY_API_KEY'),
    api_secret=os.getenv('CLOUDINARY_API_SECRET')
)

# Cloudinary Storage Configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
    'MEDIA_TAG': 'media',
    'INVALID_VIDEO_ERROR_MESSAGE': 'Please upload a valid video file.',
    'STATIC_TAG': 'static',
    'STATIC_IMAGES_EXTENSIONS': ['jpg', 'jpe', 'jpeg', 'jpc', 'jp2', 'j2k', 'wdp', 'jxr', 
                                'hdp', 'png', 'gif', 'webp', 'bmp', 'tif', 'tiff', 'ico'],
    'MAGIC_FILE_PATH': 'magic',
    'STATIC_IMAGES_TRANSFORMATIONS': {
        'default': {
            'format': 'jpg',
            'transformation': [
                {'quality': 'auto'},
                {'fetch_format': 'auto'}
            ]
        }
    },
    'STATIC_FILES_TRANSFORMATIONS': {
        'default': {
            'format': 'jpg',
            'transformation': [
                {'quality': 'auto'},
                {'fetch_format': 'auto'}
            ]
        }
    }
}

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
DJANGO_CELERY_BEAT_TZ_AWARE = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'Asia/Bangkok'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# FIREBASE
if not os.environ.get('FIREBASE_SKIP_INIT'):
    initialize_firebase()

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# JAZZMIN SETTING
JAZZMIN_SETTINGS = {
    "site_title": "OUPharmacy System",
    "site_header": "OUPharmacy System",
    "site_brand": "OUPharmacy",
    "site_logo": "logo/logo_oupharmacy_1x1w.png",
    "site_logo_classes": "img-rounded",
    "site_icon": "logo/logo_oupharmacy_1x1.png",
    "welcome_sign": "Sign in to OUPharmacy System",
    "copyright": "VO MINH HUNG",
    "search_model": "mainApp.User",
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://github.com/VoMinhHung-SR/OUPharmacyManagement", "new_window": True},
        {"model": "auth.User"},
        {"app": "books"},
    ],
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/VoMinhHung-SR/OUPharmacyManagement", "new_window": True,
         "icon": "fas fa-life-ring"},
        {"model": "mainApp.User"},
    ],
    # Jazzmin already appends "Log out" in the user menu; keep it visible via default behavior.
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "custom_links": {
        "stats": [{
            "name": "Statistics",
            "url": "stats",
            "icon": "fas fa-chart-bar",
            "permissions": [],
            "condition": lambda user: user.is_superuser,
        }]
    },
    'default_dashboard': 'admin/stats.html',
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "mainApp": "fas fa-clinic-medical",
        "mainApp.User": "fas fa-user",
        "mainApp.UserRole": "fas fa-user-tag",
        "mainApp.UserAddress": "fas fa-map-marker-alt",
        "mainApp.Patient": "fas fa-user-injured",
        "mainApp.Examination": "fas fa-stethoscope",
        "mainApp.Diagnosis": "fas fa-notes-medical",
        "mainApp.Prescribing": "fas fa-file-prescription",
        "mainApp.PrescriptionDetail": "fas fa-pills",
        "mainApp.Bill": "fas fa-file-invoice-dollar",
        "mainApp.DoctorProfile": "fas fa-user-md",
        "mainApp.DoctorSchedule": "fas fa-calendar-alt",
        "mainApp.TimeSlot": "fas fa-clock",
        "mainApp.SpecializationTag": "fas fa-tags",
        "storeApp": "fas fa-store",
        "storeApp.Brand": "fas fa-trademark",
        "storeApp.Category": "fas fa-sitemap",
        "storeApp.Product": "fas fa-box",
        "storeApp.ProductVariant": "fas fa-boxes",
        "storeApp.MedicineBatch": "fas fa-flask",
        "storeApp.Order": "fas fa-shopping-cart",
        "storeApp.OrderItem": "fas fa-receipt",
        "storeApp.PaymentMethod": "fas fa-credit-card",
        "storeApp.ShippingMethod": "fas fa-truck",
        "storeApp.Notification": "fas fa-bell",
        "storeApp.SearchKeyword": "fas fa-search",
        "storeApp.Campaign": "fas fa-bullhorn",
        "oauth2_provider": "fas fa-key",
        "oauth2_provider.Application": "fas fa-id-badge",
        "oauth2_provider.AccessToken": "fas fa-unlock-alt",
        "oauth2_provider.RefreshToken": "fas fa-sync",
        "oauth2_provider.Grant": "fas fa-hand-holding",
        "oauth2_provider.IDToken": "fas fa-fingerprint",
        "django_celery_beat": "fas fa-tasks",
        "django_celery_beat.PeriodicTask": "fas fa-redo",
        "django_celery_beat.IntervalSchedule": "fas fa-hourglass-half",
        "django_celery_beat.CrontabSchedule": "fas fa-calendar-check",
        "django_celery_beat.SolarSchedule": "fas fa-sun",
        "django_celery_beat.ClockedSchedule": "fas fa-stopwatch",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "jazzmin/custom.css",
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "language_chooser": False,
}
