# Generated by Django 4.2.21 on 2025-05-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_medicineunit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
