# Generated by Django 4.2.21 on 2025-06-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_specializationtag_doctorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
    ]
