# Generated by Django 4.2.21 on 2025-11-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_user_social_id_user_social_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineunit',
            name='brand_id',
            field=models.BigIntegerField(blank=True, help_text='ID của Brand trong store database', null=True),
        ),
    ]
