# Generated by Django 4.2.21 on 2025-12-12 14:41

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_medicineunit_brand_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['level', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='contraindications',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='medicineunit',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='medicineunit',
            name='packaging',
        ),
        migrations.RemoveField(
            model_name='medicineunit',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(default=0, help_text='Level trong hierarchy (0 = root)'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mainApp.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, help_text='category.categoryPath', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='path_slug',
            field=models.CharField(blank=True, db_index=True, help_text='category.categorySlug (unique)', max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, db_index=True, help_text='URL slug cho category (unique per parent) - auto-generated', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='adverse_effect',
            field=models.TextField(blank=True, help_text='content.adverseEffect - Tác dụng phụ', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='brand_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='basicInfo.brand - ID của Brand trong store database', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='careful',
            field=models.TextField(blank=True, help_text='content.careful - Lưu ý/Cảnh báo', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, help_text='content.description - Mô tả sản phẩm', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage',
            field=models.TextField(blank=True, help_text='content.dosage - Liều dùng', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='ingredients',
            field=models.TextField(blank=True, help_text='content.ingredients - Thành phần', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mid',
            field=models.CharField(blank=True, db_index=True, help_text='basicInfo.mid - Mã định danh sản phẩm (MID)', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='preservation',
            field=models.TextField(blank=True, help_text='content.preservation - Bảo quản', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='slug',
            field=models.CharField(blank=True, db_index=True, help_text='basicInfo.slug - URL slug', max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='usage',
            field=models.TextField(blank=True, help_text='content.usage - Cách sử dụng/Công dụng', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='web_name',
            field=models.CharField(blank=True, help_text='basicInfo.webName - Tên hiển thị trên web', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='display_code',
            field=models.IntegerField(blank=True, help_text='metadata.displayCode - Display code', null=True),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='media.images - Danh sách ảnh gallery (JSON array)'),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='metadata.isPublish - Published status'),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='link',
            field=models.URLField(blank=True, help_text='metadata.link - Link sản phẩm', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='specifications.manufacturer - Nhà sản xuất', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='origin',
            field=models.CharField(blank=True, help_text='specifications.origin - Xuất xứ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='package_size',
            field=models.CharField(blank=True, help_text='pricing.packageSize - Quy cách đóng gói', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='price_display',
            field=models.CharField(blank=True, help_text='pricing.priceDisplay - Giá hiển thị: 567.000đ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='price_obj',
            field=models.JSONField(blank=True, default=dict, help_text='pricing.priceObj - Object giá (JSON object)', null=True),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='price_value',
            field=models.FloatField(db_index=True, default=0, help_text='pricing.priceValue - Giá trị số (dùng để filter/sort)'),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='prices',
            field=models.JSONField(blank=True, default=list, help_text='pricing.prices - Danh sách giá (JSON array)'),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='product_ranking',
            field=models.IntegerField(db_index=True, default=0, help_text='metadata.productRanking - Product ranking'),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='registration_number',
            field=models.CharField(blank=True, help_text='specifications.registrationNumber - Số đăng ký', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='shelf_life',
            field=models.CharField(blank=True, help_text='specifications.shelfLife - Hạn sử dụng', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='specifications.specifications - Object specification (JSON object)', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(db_index=True, help_text='basicInfo.name', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='medicineunit',
            name='category',
            field=models.ForeignKey(blank=True, help_text='category - Category cuối cùng (leaf) trong hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.category'),
        ),
        migrations.AlterField(
            model_name='medicineunit',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', help_text='media.image - Ảnh chính', max_length=255, null=True, verbose_name='medicines'),
        ),
        migrations.AlterField(
            model_name='medicineunit',
            name='in_stock',
            field=models.IntegerField(db_index=True, default=0, help_text='Số lượng tồn kho'),
        ),
        migrations.AlterField(
            model_name='medicineunit',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='mainApp.medicine'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='mainApp_cat_slug_9f1a69_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'level'], name='mainApp_cat_parent__9ebd71_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['path_slug'], name='mainApp_cat_path_sl_9f7d33_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['mid'], name='mainApp_med_mid_74931e_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['slug'], name='mainApp_med_slug_e40b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['brand_id'], name='mainApp_med_brand_i_b724cd_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='mainApp_med_name_0ccb4a_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineunit',
            index=models.Index(fields=['is_published', 'product_ranking'], name='mainApp_med_is_publ_004408_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineunit',
            index=models.Index(fields=['category', 'is_published'], name='mainApp_med_categor_86ae14_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineunit',
            index=models.Index(fields=['price_value', 'is_published'], name='mainApp_med_price_v_97061f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineunit',
            index=models.Index(fields=['medicine', 'is_published'], name='mainApp_med_medicin_07519b_idx'),
        ),
    ]
