# Generated by Django 4.2.21 on 2026-01-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_update_medicineunit_field_lengths'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(db_index=True, help_text='Mã voucher (ví dụ: NEWUSER50)', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENT', 'Percentage')], default='PERCENT', max_length=10)),
                ('value', models.FloatField(default=0, help_text='Giá trị giảm giá (số tiền nếu FIXED, phần trăm nếu PERCENT)')),
                ('max_discount', models.FloatField(blank=True, help_text='Giảm giá tối đa (chỉ áp dụng cho PERCENT type)', null=True)),
                ('min_order_value', models.FloatField(blank=True, default=0, help_text='Giá trị đơn hàng tối thiểu để áp dụng voucher', null=True)),
                ('applicable_products', models.JSONField(blank=True, default=list, help_text='Danh sách MID sản phẩm áp dụng (empty = áp dụng tất cả)')),
                ('applicable_categories', models.JSONField(blank=True, default=list, help_text='Danh sách category slug áp dụng (empty = áp dụng tất cả)')),
                ('start_at', models.DateTimeField(blank=True, db_index=True, help_text='Ngày bắt đầu áp dụng voucher (null = áp dụng ngay)', null=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, help_text='Ngày kết thúc voucher (null = không giới hạn)', null=True)),
                ('usage_limit', models.IntegerField(blank=True, help_text='Số lần sử dụng tối đa (null = không giới hạn)', null=True)),
                ('used_count', models.IntegerField(db_index=True, default=0, help_text='Số lần đã sử dụng voucher')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Trạng thái active của voucher')),
                ('description', models.CharField(blank=True, help_text='Mô tả chương trình giảm giá', max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='is_hot',
            field=models.BooleanField(db_index=True, default=False, help_text='Sản phẩm hot/nổi bật'),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='original_price',
            field=models.CharField(blank=True, help_text='pricing.originalPrice - Giá gốc (string)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='original_price_value',
            field=models.FloatField(blank=True, db_index=True, help_text='pricing.originalPriceValue - Giá trị số của giá gốc', null=True),
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='package_options',
            field=models.JSONField(blank=True, default=list, help_text='pricing.packageOptions - Danh sách các tùy chọn đóng gói (JSON array)'),
        ),
        migrations.AddIndex(
            model_name='medicineunit',
            index=models.Index(fields=['original_price_value', 'is_published'], name='mainApp_med_origina_4b25db_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineunit',
            index=models.Index(fields=['is_hot', 'is_published'], name='mainApp_med_is_hot_a7f597_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['code'], name='mainApp_vou_code_68a584_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['is_active', 'start_at', 'end_at'], name='mainApp_vou_is_acti_5da504_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['used_count', 'usage_limit'], name='mainApp_vou_used_co_719bfd_idx'),
        ),
    ]
