# Generated by Django 4.2.21 on 2026-01-19 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_voucher_medicineunit_is_hot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENT', 'Percentage')], default='PERCENT', help_text='Loại giảm giá: FIXED (số tiền cố định) hoặc PERCENT (phần trăm)', max_length=10),
        ),
        migrations.CreateModel(
            name='MedicineUnitStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_total', models.IntegerField(db_index=True, default=0)),
                ('sold_30d', models.IntegerField(db_index=True, default=0)),
                ('sold_7d', models.IntegerField(db_index=True, default=0)),
                ('view_count', models.IntegerField(db_index=True, default=0)),
                ('wishlist_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='mainApp.medicineunit')),
            ],
        ),
    ]
