# Generated by Django 4.2.21 on 2026-02-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_remove_user_location_useraddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncity',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='commoncity',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='commondistrict',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='commondistrict',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='commoncity',
            name='id_province',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='commondistrict',
            name='id_commune',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='CommonLocation',
        ),
    ]
