# Generated by Django 4.2.21 on 2026-03-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_remove_commoncity_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineunit',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='medicineunit',
            name='package_options',
        ),
        migrations.RemoveField(
            model_name='medicineunit',
            name='price_obj',
        ),
        migrations.RemoveField(
            model_name='medicineunit',
            name='prices',
        ),
    ]
