# Generated by Django 4.2.21 on 2026-03-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_remove_medicineunit_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondetail',
            name='item_name_snapshot',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='product_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='product_variant_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='product_variant_unit_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='quantity_in_base_snapshot',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='unit_name_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='unit_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
