# Generated by Django 4.2.21 on 2026-04-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_drop_medicine_legacy_tables_store_only'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
