# Generated by Django 4.2.21 on 2026-07-14 19:04
# MASTER P1: unique (schedule, start_time, end_time) on TimeSlot.
# atomic=False: Postgres forbids ALTER TABLE after DML+triggers in the same transaction
# (error: pending trigger events) — dedupe must commit before AddConstraint.

from django.db import migrations, models


def dedupe_timeslots(apps, schema_editor):
    """Merge duplicate (schedule, start_time, end_time) so UniqueConstraint can apply."""
    TimeSlot = apps.get_model("mainApp", "TimeSlot")
    Examination = apps.get_model("mainApp", "Examination")

    seen = {}
    for slot in TimeSlot.objects.all().order_by("id").iterator():
        key = (slot.schedule_id, slot.start_time, slot.end_time)
        if key not in seen:
            seen[key] = slot.id
            continue
        keep_id = seen[key]
        Examination.objects.filter(time_slot_id=slot.id).update(time_slot_id=keep_id)
        slot.delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("mainApp", "0019_delete_voucher"),
    ]

    operations = [
        migrations.RunPython(dedupe_timeslots, noop_reverse),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                fields=("schedule", "start_time", "end_time"),
                name="uniq_timeslot_schedule_start_end",
            ),
        ),
    ]
