# Generated by Django 4.2.21 on 2025-11-02 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_column='name', max_length=120, unique=True)),
                ('active', models.BooleanField(db_column='active', default=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'store_brand',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('order_number', models.CharField(db_column='order_number', db_index=True, max_length=30, unique=True)),
                ('user_id', models.BigIntegerField(blank=True, db_column='user_id', help_text='ID của User trong database default', null=True)),
                ('shipping_address', models.TextField(db_column='shipping_address')),
                ('subtotal', models.FloatField(db_column='subtotal', default=0, help_text='Tổng tiền sản phẩm', validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_fee', models.FloatField(db_column='shipping_fee', default=0, help_text='Phí vận chuyển', validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.FloatField(db_column='total', default=0, help_text='Tổng thanh toán', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('CONFIRMED', 'Đã xác nhận'), ('SHIPPING', 'Đang giao hàng'), ('DELIVERED', 'Đã giao'), ('CANCELLED', 'Đã hủy')], db_column='status', default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, db_column='notes', help_text='Ghi chú của khách hàng', null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'store_order',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_column='name', max_length=120)),
                ('code', models.CharField(db_column='code', help_text='Mã định danh: COD, MOMO, VNPAY...', max_length=60, unique=True)),
                ('active', models.BooleanField(db_column='active', default=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'store_payment_method',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_column='name', max_length=120)),
                ('price', models.FloatField(db_column='price', default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_days', models.IntegerField(blank=True, db_column='estimated_days', help_text='Số ngày ước tính', null=True)),
                ('active', models.BooleanField(db_column='active', default=True)),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'db_table': 'store_shipping_method',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('medicine_unit_id', models.BigIntegerField(db_column='medicine_unit_id', help_text='ID của MedicineUnit trong database default')),
                ('quantity', models.PositiveIntegerField(db_column='quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.FloatField(db_column='price', help_text='Giá tại thời điểm đặt hàng (snapshot)', validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storeApp.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'store_order_item',
                'ordering': ['created_date'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(db_column='payment_method_id', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='storeApp.paymentmethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(db_column='shipping_method_id', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='storeApp.shippingmethod'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('notification_type', models.CharField(choices=[('EXPIRY_WARNING', 'Cảnh báo sắp hết hạn'), ('EXPIRY_URGENT', 'Cảnh báo khẩn cấp'), ('EXPIRED', 'Đã hết hạn'), ('LOW_STOCK', 'Tồn kho thấp')], db_column='notification_type', max_length=20)),
                ('medicine_unit_id', models.BigIntegerField(blank=True, db_column='medicine_unit_id', help_text='ID của MedicineUnit (null nếu là thông báo tổng hợp)', null=True)),
                ('batch_id', models.BigIntegerField(blank=True, db_column='batch_id', help_text='ID của MedicineBatch nếu liên quan đến batch cụ thể', null=True)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('message', models.TextField(db_column='message')),
                ('is_read', models.BooleanField(db_column='is_read', default=False)),
                ('read_at', models.DateTimeField(blank=True, db_column='read_at', null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'store_notification',
                'ordering': ['-created_date', 'is_read'],
                'indexes': [models.Index(fields=['is_read', '-created_date'], name='store_notif_is_read_b32071_idx'), models.Index(fields=['medicine_unit_id', 'notification_type'], name='store_notif_medicin_0a4a75_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('batch_number', models.CharField(db_column='batch_number', db_index=True, help_text='Mã lô thuốc', max_length=100, unique=True)),
                ('medicine_unit_id', models.BigIntegerField(db_column='medicine_unit_id', help_text='ID của MedicineUnit trong database default')),
                ('import_date', models.DateField(db_column='import_date', help_text='Ngày nhập kho')),
                ('expiry_date', models.DateField(db_column='expiry_date', help_text='Hạn sử dụng')),
                ('quantity', models.PositiveIntegerField(db_column='quantity', help_text='Số lượng nhập', validators=[django.core.validators.MinValueValidator(1)])),
                ('remaining_quantity', models.PositiveIntegerField(db_column='remaining_quantity', default=0, help_text='Số lượng còn lại')),
                ('import_price', models.FloatField(blank=True, db_column='import_price', help_text='Giá nhập kho (để tính lợi nhuận)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Medicine Batch',
                'verbose_name_plural': 'Medicine Batches',
                'db_table': 'store_medicine_batch',
                'ordering': ['expiry_date', 'import_date'],
                'indexes': [models.Index(fields=['medicine_unit_id', 'expiry_date'], name='store_medic_medicin_335050_idx'), models.Index(fields=['expiry_date', 'remaining_quantity'], name='store_medic_expiry__6ab8a9_idx')],
            },
        ),
    ]
