# Generated by Django 4.2.21 on 2026-01-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0002_brand_country'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='brand',
            new_name='store_brand_country_bf11de_idx',
            old_name='store_brand_country_active_idx',
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, db_column='country', help_text='Quốc gia sản phẩm', max_length=100, null=True),
        ),
    ]
