# Generated by Django 4.2.21 on 2026-02-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0003_rename_store_brand_country_active_idx_store_brand_country_bf11de_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('keyword', models.CharField(db_column='keyword', db_index=True, max_length=120)),
                ('hit_count', models.PositiveIntegerField(db_column='hit_count', default=1, help_text='Số lần người dùng tìm với từ khóa này')),
                ('last_searched_at', models.DateTimeField(auto_now=True, db_column='last_searched_at')),
            ],
            options={
                'verbose_name': 'Search Keyword',
                'verbose_name_plural': 'Search Keywords',
                'db_table': 'store_search_keyword',
                'ordering': ['-hit_count', '-last_searched_at'],
                'indexes': [models.Index(fields=['-hit_count'], name='store_searc_hit_cou_7b3406_idx')],
            },
        ),
    ]
