# Generated by Django 4.2.21 on 2026-03-16 16:32

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0004_searchkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=254)),
                ('slug', models.CharField(blank=True, db_index=True, help_text='URL slug cho category (unique per parent) - auto-generated', max_length=254, null=True)),
                ('level', models.PositiveIntegerField(default=0, help_text='Level trong hierarchy (0 = root)')),
                ('path', models.CharField(blank=True, help_text='category.categoryPath', max_length=500, null=True)),
                ('path_slug', models.CharField(blank=True, db_index=True, help_text='category.categorySlug (unique)', max_length=500, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'store_category',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=254, unique=True)),
                ('mid', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=300, null=True, unique=True)),
                ('web_name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('dosage', models.TextField(blank=True, null=True)),
                ('adverse_effect', models.TextField(blank=True, null=True)),
                ('careful', models.TextField(blank=True, null=True)),
                ('preservation', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'store_product',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('sku_name', models.CharField(blank=True, help_text='Tên biến thể hoặc quy cách, ví dụ: Hộp 30 viên', max_length=100, null=True)),
                ('in_stock', models.IntegerField(db_index=True, default=0)),
                ('price_display', models.CharField(blank=True, max_length=50, null=True)),
                ('price_value', models.FloatField(db_index=True, default=0)),
                ('original_price_value', models.FloatField(blank=True, db_index=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(default='', max_length=255, null=True, verbose_name='products')),
                ('images', models.JSONField(blank=True, default=list)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacturer', models.TextField(blank=True, null=True)),
                ('shelf_life', models.CharField(blank=True, max_length=100, null=True)),
                ('specifications', models.JSONField(blank=True, default=dict, null=True)),
                ('product_ranking', models.IntegerField(db_index=True, default=0)),
                ('display_code', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_hot', models.BooleanField(db_index=True, default=False)),
                ('is_default', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'store_product_variant',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_total', models.IntegerField(db_index=True, default=0)),
                ('sold_30d', models.IntegerField(db_index=True, default=0)),
                ('sold_7d', models.IntegerField(db_index=True, default=0)),
                ('view_count', models.IntegerField(db_index=True, default=0)),
                ('wishlist_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Variant Stats',
                'verbose_name_plural': 'Product Variant Stats',
                'db_table': 'store_product_variant_stats',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENT', 'Percentage')], default='PERCENT', max_length=10)),
                ('value', models.FloatField(default=0)),
                ('max_discount', models.FloatField(blank=True, null=True)),
                ('min_order_value', models.FloatField(blank=True, default=0, null=True)),
                ('applicable_products', models.JSONField(blank=True, default=list)),
                ('applicable_categories', models.JSONField(blank=True, default=list)),
                ('start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('used_count', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'db_table': 'store_voucher',
                'ordering': ['-created_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='medicinebatch',
            name='store_medic_medicin_335050_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='store_notif_medicin_0a4a75_idx',
        ),
        migrations.RemoveField(
            model_name='medicinebatch',
            name='medicine_unit_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='medicine_unit_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='medicine_unit_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='batch',
            field=models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='storeApp.medicinebatch'),
        ),
        migrations.AddField(
            model_name='productvariantstats',
            name='variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='storeApp.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='storeApp.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='storeApp.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='storeApp.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storeApp.category'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='product_variant',
            field=models.ForeignKey(db_column='product_variant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='storeApp.productvariant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='product_variant',
            field=models.ForeignKey(blank=True, db_column='product_variant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='storeApp.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(db_column='product_variant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='storeApp.productvariant'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['product_variant', 'expiry_date'], name='store_medic_product_bbf7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['product_variant', 'notification_type'], name='store_notif_product_50d32d_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['code'], name='store_vouch_code_b98f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['is_active', 'start_at', 'end_at'], name='store_vouch_is_acti_f57978_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['used_count', 'usage_limit'], name='store_vouch_used_co_21b435_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_published', 'product_ranking'], name='store_produ_is_publ_8d97cd_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['price_value', 'is_published'], name='store_produ_price_v_d5e603_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['original_price_value', 'is_published'], name='store_produ_origina_86ce6d_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_hot', 'is_published'], name='store_produ_is_hot_d4e31a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['mid'], name='store_produ_mid_315aff_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='store_produ_slug_361302_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='store_produ_name_5e57da_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='store_categ_slug_3348ec_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'level'], name='store_categ_parent__7f3d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['path_slug'], name='store_categ_path_sl_af9b4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
    ]
