# Generated by Django 4.2.21 on 2026-03-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0005_category_product_productvariant_productvariantstats_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productvariant',
            name='store_produ_origina_86ce6d_idx',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='original_price_value',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku_name',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='packing',
            field=models.CharField(blank=True, help_text='Quy cách đóng gói, ví dụ: Hộp 30 viên', max_length=100, null=True),
        ),
    ]
