# Generated by Django 4.2.21 on 2026-03-22 18:00
# Khôi phục để đồng bộ django_migrations với DB đã apply 0007 (đi cùng file squash).

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def forward_assign_product_variant_fk(apps, schema_editor):
    db = schema_editor.connection.alias
    MedicineBatch = apps.get_model('storeApp', 'MedicineBatch')
    OrderItem = apps.get_model('storeApp', 'OrderItem')
    ProductVariant = apps.get_model('storeApp', 'ProductVariant')
    pv = ProductVariant.objects.using(db).order_by('pk').first()
    if pv:
        MedicineBatch.objects.using(db).filter(product_variant_id__isnull=True).update(product_variant_id=pv.pk)
        OrderItem.objects.using(db).filter(product_variant_id__isnull=True).update(product_variant_id=pv.pk)
    else:
        MedicineBatch.objects.using(db).filter(product_variant_id__isnull=True).delete()
        OrderItem.objects.using(db).filter(product_variant_id__isnull=True).delete()
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('SET CONSTRAINTS ALL IMMEDIATE')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('storeApp', '0006_remove_productvariant_store_produ_origina_86ce6d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('quantity_in_base', models.PositiveIntegerField(default=1, help_text='1 Hộp = 30 viên, 1 Vỉ = 10 viên')),
                ('unit_name', models.CharField(db_index=True, help_text='Hộp, Vỉ, Viên, Gói...', max_length=50)),
                ('unit_order', models.PositiveIntegerField(default=0)),
                ('price_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_display', models.CharField(blank=True, max_length=50, null=True)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['unit_order', 'id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='store_produ_price_v_d5e603_idx',
        ),
        migrations.RemoveField(
            model_name='medicinebatch',
            name='import_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='display_code',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price_display',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price_value',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='shelf_life',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='specifications',
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='import_price_per_base_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='base_unit',
            field=models.CharField(blank=True, db_index=True, help_text='Đơn vị cơ sở nhỏ nhất, ví dụ: viên, gói', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='packing_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Stock Keeping Unit', max_length=100, null=True, unique=True),
        ),
        migrations.RunPython(forward_assign_product_variant_fk, noop_reverse),
        migrations.AlterField(
            model_name='medicinebatch',
            name='product_variant',
            field=models.ForeignKey(db_column='product_variant_id', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='storeApp.productvariant'),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='quantity',
            field=models.PositiveIntegerField(db_column='quantity', help_text='Số lượng nhập theo đơn vị cơ sở', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='remaining_quantity',
            field=models.PositiveIntegerField(db_column='remaining_quantity', default=0, help_text='Số lượng còn lại theo đơn vị cơ sở'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(db_column='shipping_fee', decimal_places=2, default=0, help_text='Phí vận chuyển', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(db_column='subtotal', decimal_places=2, default=0, help_text='Tổng tiền sản phẩm', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(db_column='total', decimal_places=2, default=0, help_text='Tổng thanh toán', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=2, help_text='Đơn giá snapshot theo đơn vị đã chọn (ProductVariantUnit)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(db_column='product_variant_id', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='storeApp.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='in_stock',
            field=models.IntegerField(db_index=True, default=0, help_text='Tồn kho cache theo đơn vị cơ sở (base unit)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='min_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productvariantunit',
            name='variant',
            field=models.ForeignKey(db_column='product_variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='storeApp.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant_unit',
            field=models.ForeignKey(blank=True, db_column='product_variant_unit_id', help_text='Đơn vị bán đã chọn (Hộp/Lọ/...); null = dữ liệu cũ hoặc mặc định theo variant', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='storeApp.productvariantunit'),
        ),
        migrations.AddConstraint(
            model_name='productvariantunit',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_default=True),
                fields=('variant',),
                name='store_pvu_one_default_per_variant',
            ),
        ),
        migrations.AddConstraint(
            model_name='productvariantunit',
            constraint=models.CheckConstraint(
                check=models.Q(quantity_in_base__gte=1),
                name='store_pvu_quantity_in_base_gte_1',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='productvariantunit',
            unique_together={('variant', 'unit_name')},
        ),
    ]
