# Generated by Django 4.2.21 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('storeApp', '0007_productvariantunit_and_more'),
    ]

    operations = [
        migrations.AlterField(  
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('EXPIRY_WARNING', 'Cảnh báo sắp hết hạn'),
                    ('EXPIRY_URGENT', 'Cảnh báo khẩn cấp'),
                    ('EXPIRED', 'Đã hết hạn'),
                    ('LOW_STOCK', 'Tồn kho thấp'),
                    ('ADMIN_SUPPORT', 'Liên hệ hỗ trợ'),
                    ('OTHERS', 'Khác'),
                ],
                db_column='notification_type',
                max_length=20,
            ),
        ),
    ]
