# Generated by Django 4.2.21 on 2026-04-27 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0009_searchkeyword_dedupe_and_ci_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.BigIntegerField(db_column='user_id', db_index=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CHECKED_OUT', 'Checked out'), ('ABANDONED', 'Abandoned')], db_column='status', db_index=True, default='ACTIVE', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'store_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'store_cart_item',
            },
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.BigIntegerField(db_column='user_id')),
                ('scope', models.CharField(choices=[('ORDER_DISCOUNT', 'Order Discount'), ('SHIPPING_DISCOUNT', 'Shipping Discount')], db_column='scope', max_length=30)),
                ('discount_amount', models.DecimalField(db_column='discount_amount', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Voucher Redemption',
                'verbose_name_plural': 'Voucher Redemptions',
                'db_table': 'store_voucher_redemption',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(db_column='discount_amount', decimal_places=2, default=0, help_text='Số tiền giảm từ voucher giảm đơn', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='order_voucher',
            field=models.ForeignKey(blank=True, db_column='order_voucher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_discount_orders', to='storeApp.voucher'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_discount_amount',
            field=models.DecimalField(db_column='shipping_discount_amount', decimal_places=2, default=0, help_text='Số tiền giảm từ voucher giảm phí ship', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_voucher',
            field=models.ForeignKey(blank=True, db_column='shipping_voucher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_discount_orders', to='storeApp.voucher'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='per_user_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='scope',
            field=models.CharField(choices=[('ORDER_DISCOUNT', 'Order Discount'), ('SHIPPING_DISCOUNT', 'Shipping Discount')], db_index=True, default='ORDER_DISCOUNT', max_length=30),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['scope', 'is_active', 'start_at', 'end_at'], name='store_vouch_scope_db85db_idx'),
        ),
        migrations.AddField(
            model_name='voucherredemption',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='voucher_redemptions', to='storeApp.order'),
        ),
        migrations.AddField(
            model_name='voucherredemption',
            name='voucher',
            field=models.ForeignKey(db_column='voucher_id', on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='storeApp.voucher'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(db_column='cart_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storeApp.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(db_column='product_variant_id', on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='storeApp.productvariant'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variant_unit',
            field=models.ForeignKey(blank=True, db_column='product_variant_unit_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='storeApp.productvariantunit'),
        ),
        migrations.AddField(
            model_name='cart',
            name='checkout_order',
            field=models.ForeignKey(blank=True, db_column='checkout_order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_carts', to='storeApp.order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_voucher',
            field=models.ForeignKey(blank=True, db_column='order_voucher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_discount_carts', to='storeApp.voucher'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_method',
            field=models.ForeignKey(blank=True, db_column='shipping_method_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='storeApp.shippingmethod'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_voucher',
            field=models.ForeignKey(blank=True, db_column='shipping_voucher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_discount_carts', to='storeApp.voucher'),
        ),
        migrations.AddIndex(
            model_name='voucherredemption',
            index=models.Index(fields=['voucher', 'user_id'], name='store_vouch_voucher_81d1c4_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherredemption',
            index=models.Index(fields=['order'], name='store_vouch_order_i_99eaa7_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherredemption',
            index=models.Index(fields=['user_id', 'created_date'], name='store_vouch_user_id_f7f5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'updated_date'], name='store_cart__cart_id_bfa6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product_variant'], name='store_cart__product_bb625b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product_variant', 'product_variant_unit'), name='store_cart_item_unique_variant_unit'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user_id', 'status'], name='store_cart_user_id_6ecadc_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', 'updated_date'], name='store_cart_status_0869a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user_id',), name='store_cart_one_active_per_user'),
        ),
    ]
