# Generated by Django 4.2.21 on 2026-05-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0010_cart_cartitem_voucherredemption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Exactly one primary row per product when assigned')),
                ('sort_order', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
                'db_table': 'store_product_category',
                'ordering': ['product_id', '-is_primary', 'sort_order', 'category_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='store_cart_one_active_per_user',
        ),
        migrations.AddField(
            model_name='cart',
            name='guest_session_id',
            field=models.UUIDField(blank=True, db_column='guest_session_id', db_index=True, default=None, help_text='Anonymous cart session (UUID from X-Guest-Session header)', null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.BigIntegerField(blank=True, db_column='user_id', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary category (canonical URL); kept in sync with ProductCategory.is_primary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='storeApp.category'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['guest_session_id', 'status'], name='store_cart_guest_s_fca32e_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE'), ('user_id__isnull', False)), fields=('user_id',), name='store_cart_one_active_per_user'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_session_id__isnull', False), ('status', 'ACTIVE')), fields=('guest_session_id',), name='store_cart_one_active_per_guest'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('guest_session_id__isnull', True), ('user_id__isnull', False)), models.Q(('guest_session_id__isnull', False), ('user_id__isnull', True)), _connector='OR'), name='store_cart_user_xor_guest'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='storeApp.category'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='storeApp.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='All category assignments (primary + additional); logic/backfill in follow-up tasks', related_name='categorized_products', through='storeApp.ProductCategory', to='storeApp.category'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['category', 'product'], name='st_pc_cat_prod_ix'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['product', 'is_primary'], name='st_pc_prod_pri_ix'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('product', 'category'), name='store_product_category_unique_product_category'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='store_product_category_one_primary_per_product'),
        ),
    ]
