# Generated by Django 4.2.21 on 2026-07-30 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0011_productcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.SlugField(db_column='code', help_text='Stable key used in attrs= query params (e.g. skin_type).', max_length=64, unique=True)),
                ('label', models.CharField(db_column='label', max_length=120)),
                ('facet_type', models.CharField(choices=[('multiple', 'Multiple'), ('single', 'Single')], db_column='facet_type', default='multiple', max_length=16)),
                ('sort_order', models.PositiveIntegerField(db_column='sort_order', default=100)),
                ('is_filterable', models.BooleanField(db_column='is_filterable', default=True)),
            ],
            options={
                'db_table': 'store_catalog_attribute',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CatalogAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(db_column='slug', max_length=120)),
                ('label', models.CharField(db_column='label', max_length=160)),
                ('sort_order', models.PositiveIntegerField(db_column='sort_order', default=100)),
                ('attribute', models.ForeignKey(db_column='attribute_id', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='storeApp.catalogattribute')),
            ],
            options={
                'db_table': 'store_catalog_attribute_option',
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('option', models.ForeignKey(db_column='option_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='storeApp.catalogattributeoption')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='storeApp.product')),
            ],
            options={
                'db_table': 'store_product_attribute_value',
            },
        ),
        migrations.AddIndex(
            model_name='catalogattribute',
            index=models.Index(fields=['is_filterable', 'sort_order'], name='store_catal_is_filt_9b5cab_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['option', 'product'], name='store_produ_option__706b24_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'option'), name='uniq_store_pav_product_option'),
        ),
        migrations.AddIndex(
            model_name='catalogattributeoption',
            index=models.Index(fields=['attribute', 'sort_order'], name='store_catal_attribu_9a8531_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogattributeoption',
            constraint=models.UniqueConstraint(fields=('attribute', 'slug'), name='uniq_store_attr_option_attr_slug'),
        ),
    ]
