# Generated by Django 4.2.21 on 2026-08-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0012_catalog_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(db_column='name', max_length=120)),
                ('slug', models.SlugField(db_column='slug', max_length=80, unique=True)),
                ('title', models.CharField(db_column='title', max_length=160)),
                ('subtitle', models.CharField(blank=True, db_column='subtitle', max_length=255, null=True)),
                ('description_html', models.TextField(blank=True, db_column='description_html', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended'), ('archived', 'Archived')], db_column='status', db_index=True, default='draft', max_length=20)),
                ('priority', models.IntegerField(db_column='priority', default=0)),
                ('start_at', models.DateTimeField(blank=True, db_column='start_at', db_index=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, db_column='end_at', db_index=True, null=True)),
                ('locale', models.CharField(db_column='locale', default='vi', max_length=10)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='created_by_id', db_index=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='updated_by_id', null=True)),
                ('version', models.PositiveIntegerField(db_column='version', default=1)),
            ],
            options={
                'db_table': 'store_campaign',
                'ordering': ['-priority', 'start_at', 'id'],
                'permissions': [('campaign_view', 'Can view store campaigns'), ('campaign_manage', 'Can manage store campaigns')],
            },
        ),
        migrations.CreateModel(
            name='CampaignPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('slot', models.CharField(choices=[('HOME_HERO', 'Home hero'), ('HOME_PROMO_LEFT', 'Home promo left'), ('HOME_PROMO_RIGHT', 'Home promo right'), ('HOME_STRIP', 'Home strip'), ('CATEGORY_BANNER', 'Category banner'), ('SEARCH_BANNER', 'Search banner')], db_column='slot', db_index=True, max_length=40)),
                ('title', models.CharField(db_column='title', max_length=160)),
                ('subtitle', models.CharField(blank=True, db_column='subtitle', max_length=255, null=True)),
                ('cta_label', models.CharField(blank=True, db_column='cta_label', max_length=80, null=True)),
                ('cta_url', models.CharField(blank=True, db_column='cta_url', max_length=500, null=True)),
                ('image_desktop_url', models.CharField(blank=True, db_column='image_desktop_url', max_length=500, null=True)),
                ('image_mobile_url', models.CharField(blank=True, db_column='image_mobile_url', max_length=500, null=True)),
                ('image_alt', models.CharField(blank=True, db_column='image_alt', max_length=160, null=True)),
                ('sort_order', models.IntegerField(db_column='sort_order', default=0)),
                ('is_enabled', models.BooleanField(db_column='is_enabled', default=True)),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='storeApp.campaign')),
            ],
            options={
                'db_table': 'store_campaign_placement',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'start_at', 'end_at'], name='campaign_status_window_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['-priority', 'start_at'], name='campaign_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(('end_at__isnull', True), ('start_at__isnull', True), ('end_at__gt', models.F('start_at')), _connector='OR'), name='campaign_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'scheduled', 'active', 'paused', 'ended', 'archived'])), name='campaign_status_valid'),
        ),
        migrations.AddIndex(
            model_name='campaignplacement',
            index=models.Index(fields=['campaign', 'slot'], name='placement_campaign_slot_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignplacement',
            index=models.Index(fields=['slot', 'is_enabled'], name='placement_slot_enabled_idx'),
        ),
    ]
